#Set working directory
workdir: "$HOME/scratch/admixture_analysis"

#Set sample names
SAMPLES: ["BH10_F1_1", "BH10_F1_2", "BH10_F2_1", "BH10_F2_2"]

#Set population names and samples for Fst computation
POP_1: "Col_Head"
POP_2: "Col_Body"

#Set reference genome name
GENOME: "p_humanus_reference.fa"

#Define important paths
ADAPTERS: "/storage/work/cxb585/bin/Trimmomatic-0.36/adapters/TruSeq3-PE.fa"
GATK: "/storage/work/cxb585/bin/GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar"
PDGSPIDER: "/storage/work/cah422/bin/PGDSpider_2.1.1.3/PGDSpider2-cli.jar"
PICARD: "/storage/work/cxb585/bin/picard-2.10.10/picard.jar"
TRIMMOMATIC: "/storage/work/cxb585/bin/Trimmomatic-0.36/trimmomatic-0.36.jar"

#Select modules to load
MODULES: ["bamtools", "bcftools", "bwa", "gatk", "picard", "python", "pdgspider", "samtools", "trimmomatic", "vcftools"]
